name: Check if the project is building

on:
  push

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install essential
      run: sudo apt install build-essential clang

    - name: Get specific version CMake, v3.17.0
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.17.0

    - name: Make project with GCC
      run: |
        mkdir -p build_gxx
        cd build_gxx
        cmake -G "Unix Makefiles" -DLoggifyer_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=g++ ..
        cmake --build .
        cd ..
        ./tests/Loggifyer_test

    - name: Make project with Clang
      run: |
        mkdir -p build_clang
        cd build_clang
        cmake -G "Unix Makefiles" -DLoggifyer_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=clang++ ..
        cmake --build .
        cd ..
        ./tests/Loggifyer_test
