name: Check if the project is building

on:
  push

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install essential
      run: sudo apt install build-essential clang

    - name: Get specific version CMake, v3.17.0
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.17.0

    - name: Make project with GCC
      run: |
        mkdir -p build
        cd build
        cmake -G "Unix Makefiles" -DLoggifyer_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=g++ ..
        cmake --build .
        ./tests/Loggifyer_test

    - name: Make project with Clang
      run: |
        mkdir -p build_clang
        cd build_clang
        cmake -G "Unix Makefiles" -DLoggifyer_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=clang++ ..
        cmake --build .
        ./tests/Loggifyer_test

  build-test-windows:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: install Visual Studio 2019
        run: choco install visualstudio2019buildtools
      - name: install MSVC
        run: choco install vswhere
      - name: Set environment variable
        run: setx /M VSWherePath "C:\ProgramData\chocolatey\bin\vswhere.exe"
      - name: Add VS to PATH
        run: setx /M PATH "%PATH%;%VSWherePath%\vs16\Community\VC\Auxiliary\Build"
      - name: make project with msvc
        run: |
          mkdir -p build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DLoggifyer_BUILD_TESTS=ON ..
          cmake --build . --config Release
